kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "panop.fullname" . }}
  labels: {{ include "panop.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{ include "panop.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels: {{ include "panop.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "panop.fullname" . }}-job-sa
      imagePullSecrets:
        - name: panop-exocr
        - name: panop-ghcr
      containers:
        - name: {{ include "panop.fullname" . }}
          image: {{.Values.image.repository}}-{{ .Chart.Name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            - name: PANOP_ENGINE
              value: {{ .Values.engine }}
            - name: PANOP_DOMAIN
              value: {{ .Values.domain }}
            - name: PANOP_LOGLEVEL
              value: {{ .Values.loglevel }}
            - name: CONF_INPUT.CONCURRENCY
              value: "{{ .Values.concurrency }}"
            - name: PANOP_SCANNER_APPVERSION
              value: {{ .Values.scanner.appversion }}
            - name: PANOP_SCANNER_REGISTRY
              value: {{ .Values.scanner.registry }}
            - name: PANOP_SCANNER_IMAGE
              value: {{ .Values.scanner.image }}
            - name: PANOP_SCANNER_LOGLEVEL
              value: {{ .Values.scanner.loglevel }}
            - name: PANOP_SCANNER_TYPE
              value: ""
            - name: PANOP_SCANNER_ID
              valueFrom:
                secretKeyRef:
                  {{- if eq .Values.secret "-" }}
                  name: {{ include "panop.fullname" . }}
                  {{- else }}
                  name: {{ .Values.secret }}
                  {{- end }}
                  key: panop-global-scanner-id
            - name: PANOP_SCANNER_RATELIMIT
              value: "{{ .Values.scanner.ratelimit | default 20 }}"
            - name: PANOP_SCANNER_TEMPLATE_CONCURRENCY
              value: "{{ .Values.scanner.template_concurrency | default 25 }}"
            - name: PANOP_SCANNER_LIMIT_MEMORY
              value: "{{ .Values.scanner.limit_memory | default "1000Mi" }}"
            - name: PANOP_SCANNER_PULLSECRET
              value: {{ .Values.scanner.pullsecret }}
            - name: PANOP_SCANNER_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if eq .Values.secret "-" }}
                  name: {{ include "panop.fullname" . }}
                  {{- else }}
                  name: {{ .Values.secret }}
                  {{- end }}
                  key: panop-managed-scanner-token
            - name: PANOP_KUBERNETES_NODETYPE
              value: {{ .Values.engine }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}