apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "panop.fullname" . }}-job-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]