apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "panop.fullname" . }}-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "panop.fullname" . }}-job-sa
roleRef:
  kind: Role
  name: {{ include "panop.fullname" . }}-job-role
  apiGroup: rbac.authorization.k8s.io
