apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nuclei-job-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
