apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nuclei-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: nuclei-job-sa
roleRef:
  kind: Role
  name: nuclei-job-role
  apiGroup: rbac.authorization.k8s.io
