apiVersion: v1
stringData:
  nuclei-user-certificate: |
    -----BEGIN PD NUCLEI USER CERTIFICATE-----
    MIIBRzCB7aADAgECAgRls3pHMAoGCCqGSM49BAMCMBAxDjAMBgNVBAMTBXBhbm9w
    MB4XDTI0MDEyNjA5MjQyM1oXDTI4MDEyNTA5MjQyM1owEDEOMAwGA1UEAxMFcGFu
    b3AwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR3FrzGuv4JTsDPGfOARUCR3q3/
    EBLfceMU/xamzfrWfwS3yY6jd5jG+GwgAQ0n3dea25y9vGNsHkUkyGSYWHB1ozUw
    MzAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/
    BAIwADAKBggqhkjOPQQDAgNJADBGAiEA4WwRsgLpIqFen/sfexdTWSZVtjBJsLXq
    JsL3BQhpzksCIQC8bSDDNjO0D+U4y9pWIyaZGU6bsHsumFt6HVWayrLkVw==
    -----END PD NUCLEI USER CERTIFICATE-----
  panop-global-scanner-id: "scaner id"
  panop-managed-scanner-token: "token"
immutable: false
kind: Secret
metadata:
  name: panop-svc-httpjobs
type: Opaque
