{{ if eq .Values.existingImageCredentials "-"}}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" . }}

immutable: false
kind: Secret
metadata:
  name: {{ include "panop.fullname" . }}-cr
type: kubernetes.io/dockerconfigjson
{{ end}}