apiVersion: v1
kind: Service
metadata:
  name: {{ include "panop.fullname" . }}
  labels: {{ include "panop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 8080
      port: 8080
      protocol: TCP
  selector: {{ include "panop.selectorLabels" . | nindent 6 }}
