domain: prod
engine: kubernetes

image:
  repository: exo.container-registry.com/panop/panop
  pullPolicy: IfNotPresent
replicas: 1

imageCredentials:
  - registry: exo.container-registry.com
    username: ""
    accessToken: ""
        
existingImageCredentials: "-"

concurrency: 5 ## number jobs launch concurrently

secret: "-"   # create or use existing secret

resources:
  limits:
    cpu: 500m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 200Mi

loglevel: info

## if you want node selector
kubernetes:
  tolerations:
   - key: "dedicated"
     operator: "Equal"
     value: "foo"
     effect: "NoSchedule"
#   - key: "env"
#     operator: "Equal"
#     value: "bar"
#     effect: "NoSchedule"
  nodeSelector:
#    nodeType: "standard" 


scanner:
  id: <scanner id>
  token: <tower token>
  namespace: default
  ratelimit: 20  
  appversion: latest
  registry: exo.container-registry.com/panop/panop-svc-scanner
  image: panop-scanner-offensive
  loglevel: info
  limit_memory: 1800Mi


