domain: dev
engine: kubernetes

image:
  repository: exo.container-registry.com/panop/panop
  pullPolicy: IfNotPresent

replicas: 1

concurrency: 5

resources:
  limits:
    cpu: 500m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 200Mi

loglevel: info

aws:
  region: eu-central-1

cpuAverageUtilization: 10
nodeSelector:  
#   nodeType: standard 
  
scanner:
  id: 999
  token: abcd
  ratelimit: 20  
  appversion: latest
  registry: exo.container-registry.com/panop/panop-svc-scanner
  image: panop-scanner-offensive
  loglevel: info
  limit_memory: 1800Mi
  pullsecret: panop-exocr

